sudo: true
dist: xenial

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/now:10-alpine .
      - docker push $DOCKER_USERNAME/now:10-apline
